Web/Controllers/RadioController.cs
using Kendo.Mvc.UI;
using RadioHistoryService;
using RadioService;
using SearchDataService;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using SystemInfoService;
using TalkgroupRadioService;
using TowerRadioService;
using TowerTalkgroupRadioService;
using Web.Helpers;
using static Web.Helpers.Factory;

namespace Web.Controllers
{
    public class RadioController : BaseController
    {
        private const string GRID_LAYOUT = "_GridLayout";

        private readonly ISystemInfoService _systemInfoService;
        private readonly IRadioService _radioService;
        private readonly ITowerRadioService _towerRadioService;
        private readonly ITowerTalkgroupRadioService _towerTalkgroupRadioService;
        private readonly ITalkgroupRadioService _talkgroupRadioService;
        private readonly IRadioHistoryService _radioHistoryService;
        private readonly ISearchDataService _searchDataService;

        public RadioController(ISystemInfoService systemInfoService, IRadioService radioService, ITowerRadioService towerRadioService,
            ITalkgroupRadioService talkgroupRadioService, ITowerTalkgroupRadioService towerTalkgroupRadioService, IRadioHistoryService radioHistoryService,
            ISearchDataService searchDataService)
        {
            _systemInfoService = systemInfoService;
            _radioService = radioService;
            _towerRadioService = towerRadioService;
            _talkgroupRadioService = talkgroupRadioService;
            _towerTalkgroupRadioService = towerTalkgroupRadioService;
            _radioHistoryService = radioHistoryService;
            _searchDataService = searchDataService;
        }

        public async Task<ActionResult> Index(string systemID, int radioID)
        {
            try
            {
                ViewBag.Title = "Radio";

                return View(await _radioService.GetDetailAsync(await _systemInfoService.GetAsync(systemID), radioID,
                    _searchDataService.GetView(Request.Form[FilterDataHelper.SEARCH_DATA])));
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }

        public ActionResult Talkgroups(string systemID, int radioID)
        {
            try
            {
                var model = CreateRadioModel(systemID, radioID);

                return View(nameof(Talkgroups), GRID_LAYOUT, model);
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }

        public ActionResult Towers(string systemID, int radioID)
        {
            try
            {
                var model = CreateRadioModel(systemID, radioID);

                return View(nameof(Towers), GRID_LAYOUT, model);
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }

        public ActionResult History(string systemID, int radioID)
        {
            try
            {
                var model = CreateRadioModel(systemID, radioID);

                return View(nameof(History), GRID_LAYOUT, model);
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }

        public ActionResult TalkgroupsByTower(string systemID, int radioID)
        {
            try
            {
                var model = CreateRadioModel(systemID, radioID);

                return View(nameof(TalkgroupsByTower), GRID_LAYOUT, model);
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }

        public async Task<ActionResult> GetTowers(string systemID, int radioID, string searchData, [DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var filterDataHelper = CreateFilterDataHelper(FilterDataHelper.TOWER);
                var filterData = filterDataHelper.ConvertRequest(request, _searchDataService.Create(searchData));
                var (radioTowers, recordCount) = await _towerRadioService.GetTowersForRadioAsync(systemID, radioID, filterData);

                return Json(new
                {
                    Data = radioTowers,
                    Total = recordCount
                });
            }
            catch (Exception exception)
            {
                return HandleJSONError(exception);
            }
        }

        public async Task<ActionResult> GetTalkgroups(string systemID, int radioID, string searchData, [DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var filterDataHelper = CreateFilterDataHelper(FilterDataHelper.TALKGROUP);
                var filterData = filterDataHelper.ConvertRequest(request, _searchDataService.Create(searchData));
                var (radioTalkgroups, recordCount) = await _talkgroupRadioService.GetTalkgroupsForRadioAsync(systemID, radioID, filterData);

                return Json(new
                {
                    Data = radioTalkgroups,
                    Total = recordCount
                });
            }
            catch (Exception exception)
            {
                return HandleJSONError(exception);
            }
        }

        public async Task<ActionResult> GetHistory(string systemID, int radioID, string searchData, [DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var filterDataHelper = CreateFilterDataHelper(FilterDataHelper.RADIO);
                var filterData = filterDataHelper.ConvertRequest(request);
                var (radioHistory, recordCount) = await _radioHistoryService.GetForRadioAsync(systemID, radioID, filterData);

                return Json(new
                {
                    Data = radioHistory,
                    Total = recordCount
                });
            }
            catch (Exception exception)
            {
                return HandleJSONError(exception);
            }
        }

        public async Task<ActionResult> GetTowerList(string systemID, int radioID, string searchData, [DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var filterDataHelper = CreateFilterDataHelper(FilterDataHelper.TOWER);
                var filterData = filterDataHelper.ConvertRequest(request, _searchDataService.Create(searchData));
                var results = await _towerRadioService.GetTowerListForRadioAsync(systemID, radioID, filterData);

                return Json(results, JsonRequestBehavior.AllowGet);
            }
            catch (Exception exception)
            {
                return HandleJSONError(exception);
            }
        }

        public async Task<ActionResult> GetDateList(string systemID, int radioID, int towerNumber, string searchData, [DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var filterDataHelper = CreateFilterDataHelper(FilterDataHelper.TOWER);
                var filterData = filterDataHelper.ConvertRequest(request, _searchDataService.Create(searchData));
                var results = await _towerRadioService.GetDateListForTowerRadioAsync(systemID, radioID, towerNumber, filterData);

                return Json(results, JsonRequestBehavior.AllowGet);
            }
            catch (Exception exception)
            {
                return HandleJSONError(exception);
            }
        }

        public async Task<ActionResult> GetTowerTalkgroups(string systemID, int radioID, int towerNumber, DateTime? date, string searchData,
            [DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var filterDataHelper = CreateFilterDataHelper(FilterDataHelper.RADIO);
                var filterData = filterDataHelper.ConvertRequest(request, _searchDataService.Create(searchData));
                var (towerTalkgroups, recordCount) = await _towerTalkgroupRadioService.GetTalkgroupsForTowerRadioAsync(systemID, radioID, towerNumber,
                    date, filterData);

                return Json(new
                {
                    Data = towerTalkgroups,
                    Total = recordCount
                });
            }
            catch (Exception exception)
            {
                return HandleJSONError(exception);
            }
        }
    }
}

Web/Controllers/SystemController.cs
using Kendo.Mvc.UI;
using PatchService;
using ProcessedFileService;
using RadioService;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using SystemDetailService;
using TalkgroupService;
using TowerService;
using Web.Helpers;
using static Web.Helpers.Factory;

namespace Web.Controllers
{
    public class SystemController : BaseController
    {
        private const string GRID_LAYOUT = "_GridLayout";

        private readonly ISystemDetailService _systemDetailService;
        private readonly ITalkgroupService _talkgroupService;
        private readonly IRadioService _radioService;
        private readonly ITowerService _towerService;
        private readonly IPatchService _patchService;
        private readonly IProcessedFileService _processedFileService;

        public SystemController(ISystemDetailService systemDetailService, ITalkgroupService talkgroupService, IRadioService radioService,
            ITowerService towerService, IPatchService patchService, IProcessedFileService processedFileService)
        {
            _systemDetailService = systemDetailService;
            _talkgroupService = talkgroupService;
            _radioService = radioService;
            _towerService = towerService;
            _patchService = patchService;
            _processedFileService = processedFileService;
        }

        public async Task<ActionResult> Index(string systemID)
        {
            try
            {
                var systemInfo = await _systemDetailService.GetAsync(systemID);

                ViewBag.Title = "System Info";
                return View(systemInfo);
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }

        public ActionResult Talkgroups(string systemID)
        {
            try
            {
                var model = CreateSystemModel(systemID);

                return View(nameof(Talkgroups), GRID_LAYOUT, model);
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }

        public ActionResult Radios(string systemID)
        {
            try
            {
                var model = CreateSystemModel(systemID);

                return View(nameof(Radios), GRID_LAYOUT, model);
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }

        public ActionResult Towers(string systemID)
        {
            try
            {
                var model = CreateSystemModel(systemID);

                return View(nameof(Towers), GRID_LAYOUT, model);
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }

        public ActionResult Patches(string systemID)
        {
            try
            {
                var model = CreateSystemModel(systemID);

                return View(nameof(Patches), GRID_LAYOUT, model);
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }

        public ActionResult ProcessedFiles(string systemID)
        {
            try
            {
                var model = CreateSystemModel(systemID);

                return View(nameof(ProcessedFiles), GRID_LAYOUT, model);
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }

        [ValidateInput(false)]
        public async Task<ActionResult> GetTalkgroups(string systemID, bool activeOnly, DateTime? dateFrom, DateTime? dateTo,
            [DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var filterDataHelper = CreateFilterDataHelper(FilterDataHelper.TALKGROUP);
                var filterData = filterDataHelper.ConvertRequest(request, dateFrom, dateTo);
                var (talkgroups, recordCount) = await _talkgroupService.GetViewForSystemAsync(systemID, activeOnly, filterData);

                return Json(new
                {
                    Data = talkgroups,
                    Total = recordCount
                });
            }
            catch (Exception exception)
            {
                return HandleJSONError(exception);
            }
        }

        [ValidateInput(false)]
        public async Task<ActionResult> GetRadios(string systemID, bool activeOnly, DateTime? dateFrom, DateTime? dateTo,
            [DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var filterDataHelper = CreateFilterDataHelper(FilterDataHelper.RADIO);
                var filterData = filterDataHelper.ConvertRequest(request, dateFrom, dateTo);
                var (radios, recordCount) = await _radioService.GetViewForSystemAsync(systemID, activeOnly, filterData);

                return Json(new
                {
                    Data = radios,
                    Total = recordCount
                });
            }
            catch (Exception exception)
            {
                return HandleJSONError(exception);
            }
        }

        public async Task<ActionResult> GetTowers(string systemID, bool activeOnly, DateTime? dateFrom, DateTime? dateTo,
            [DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var filterDataHelper = CreateFilterDataHelper(FilterDataHelper.TOWER);
                var filterData = filterDataHelper.ConvertRequest(request, dateFrom, dateTo);
                var (towers, recordCount) = await _towerService.GetViewForSystemAsync(systemID, activeOnly, filterData);

                return Json(new
                {
                    Data = towers,
                    Total = recordCount
                });
            }
            catch (Exception exception)
            {
                return HandleJSONError(exception);
            }
        }

        public async Task<ActionResult> GetPatches(string systemID, DateTime? dateFrom, DateTime? dateTo, [DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var filterDataHelper = CreateFilterDataHelper(FilterDataHelper.TALKGROUP_FROM, FilterDataHelper.TALKGROUP_TO);
                var filterData = filterDataHelper.ConvertRequest(request, dateFrom, dateTo);
                var (patches, recordCount) = await _patchService.GetSummaryForSystemAsync(systemID, filterData);

                return Json(new
                {
                    Data = patches,
                    Total = recordCount
                });
            }
            catch (Exception exception)
            {
                return HandleJSONError(exception);
            }
        }

        public async Task<ActionResult> GetProcessedFiles(string systemID, [DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                var filterDataHelper = CreateFilterDataHelper(FilterDataHelper.FILE);
                var filterData = filterDataHelper.ConvertRequest(request);
                var (processedFiles, recordCount) = await _processedFileService.GetViewForSystemAsync(systemID, filterData);

                return Json(new
                {
                    Data = processedFiles,
                    Total = recordCount
                });
            }
            catch (Exception exception)
            {
                return HandleJSONError(exception);
            }
        }
    }
}

Web/Views/Tower/Frequencies.cshtml
@using TowerFrequencyService
@using TowerService

@model TowerDetailViewModel

@(Html.Kendo().Grid<TowerFrequencyViewModel>()
    .Name("FrequenciesGrid")
    .Columns(column =>
    {
        column.Bound(col => col.Frequency)
            .Width(150)
            .Filterable(false);
        column.Bound(col => col.Usage)
            .Filterable(false);
        column.Bound(col => col.VoiceCount)
            .Title("Voice")
            .Format("{0:#,##0}")
            .Filterable(false);
        column.Bound(col => col.EncryptedCount)
            .Title("Encrypted")
            .Format("{0:#,##0}")
            .Filterable(false);
        column.Bound(col => col.DataCount)
            .Title("Data")
            .Format("{0:#,##0}")
            .Filterable(false);
        column.Bound(col => col.CWIDCount)
            .Title("CWID")
            .Format("{0:#,##0}")
            .Filterable(false);
        column.Bound(col => col.AlertCount)
            .Title("Alerts")
            .Format("{0:#,##0}")
            .Filterable(false);
        column.Bound(col => col.FirstSeen)
            .Format("{0:MM-dd-yyyy HH:mm}")
            .Width(150)
            .Filterable(true);
        column.Bound(col => col.LastSeen)
            .Format("{0:MM-dd-yyyy HH:mm}")
            .Width(150)
            .Filterable(true);
    })
    .ToolBar(toolbar =>
    {
        toolbar.Template(@<text>
                            <div style="vertical-align: middle;">
                                <div class="toolbar-category">
                                    @( Html.Kendo().DropDownList()
                                                    .Name("FrequencyTypeDropDownList")
                                                    .Items(dropDown =>
                                                    {
                                                        dropDown.Add().Text("Current").Value("Current");
                                                        dropDown.Add().Text("Not Current").Value("Not Current");
                                                        dropDown.Add().Text("All").Value("All");
                                                                                    })
                                                    .HtmlAttributes(new { @class = "active-dropdown" })
                                                    .Events(events => events.Change("TowerFrequencyDropDownListChange")))
                                </div>
                            </div>
                            <div class="toolbar-export">
                                <a href="#" class="k-button k-button-icontext k-grid-excel" title="Export data to Excel">
                                    <span class="k-icon k-i-excel"></span>Export
                                </a>
                            </div>
                        </text>);
            })
    .Filterable(filter =>
    {
        filter.Enabled(true);
        filter.Operators(operators =>
        {
            operators.ForNumber(number =>
                number.Clear()
                    .IsGreaterThanOrEqualTo(">=")
                    .IsLessThanOrEqualTo("<="));

            operators.ForString(str =>
                str.Clear()
                    .Contains("Contains"));

            operators.ForDate(date =>
                date.Clear()
                    .IsGreaterThanOrEqualTo(">=")
                    .IsLessThanOrEqualTo("<="));
        });
    })
    .Scrollable(scroll => scroll.Height(575))
    .Sortable(sort =>
        sort.SortMode(GridSortMode.SingleColumn)
            .AllowUnsort(false))
    .Pageable(pageable =>
        pageable.Input(true)
            .Refresh(true))
    .Selectable(selectable =>
        selectable.Mode(GridSelectionMode.Single)
            .Type(GridSelectionType.Row))
    .Events(events =>
        events.Change("FrequenciesGrid.FrequencyChange")
            .FilterMenuInit("Filters.TowerFilterFormats"))
    .Excel(excel =>
        excel.AllPages(true)
            .Filterable(true)
            .FileName($"TowerFrequencies-{Model.SystemID}-{Model.TowerNumber}.xlsx"))
    .DataSource(dataSource =>
        dataSource.Ajax()
            .PageSize(15)
            .ServerOperation(true)
            .Sort(sort => sort.Add("Frequency").Ascending())
            .Read(read => read.Action("GetFrequencies", "Tower", new { systemID = Model.SystemID, towerNumber = Model.TowerNumber })
                .Data("GetFrequencySearchData"))))

Web/Views/Tower/Index.cshtml
@using TowerService;

@model TowerDataViewModel

<div id="SystemInfoDiv" class="card">
    <div class="card-header">
        <h3>
            <a href="@Url.Action("Index", "System", new {id = Model.SystemID})">System @Model.SystemID </a> (@Model.SystemName) / Tower @Model.TowerData.TowerNumber (@Model.TowerData.TowerName)
        </h3>
    </div>
</div>
@if ((Model.SearchData.SearchData != null) && Model.SearchData.SearchData.IsFiltered)
{
    @Html.Partial("_FilterDetail", Model.SearchData)
}
<div class="row">
    <div class="col">
        @(Html.Kendo().TabStrip()
            .Name("TowerTabs")
            .Items(tabStrip =>
            {
                tabStrip.Add()
                    .Text("Frequencies")
                    .Selected(true)
                    .LoadContentFrom("Frequencies", "Tower", new { systemID = Model.SystemID, towerNumber = Model.TowerNumber });
                tabStrip.Add()
                    .Text("Neighbors")
                    .LoadContentFrom("Neighbors", "Tower", new { systemID = Model.SystemID, towerNumber = Model.TowerNumber });
                tabStrip.Add()
                    .Text("Talkgroups")
                    .LoadContentFrom("Talkgroups", "Tower", new { systemID = Model.SystemID, towerNumber = Model.TowerNumber });
                tabStrip.Add()
                    .Text("Radios")
                    .LoadContentFrom("Radios", "Tower", new { systemID = Model.SystemID, towerNumber = Model.TowerNumber });
                tabStrip.Add()
                    .Text("Patches")
                    .LoadContentFrom("Patches", "Tower", new { systemID = Model.SystemID, towerNumber = Model.TowerNumber });
            })
            .HtmlAttributes(new { @class = "tab-strip" }))
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        var _systemID = "@Model.SystemID",
            _towerNumber = "@Model.TowerNumber",
            _viewFrequencyURL = "@Url.Action("Index", "Frequency")",
            _viewTalkgroupURL = "@Url.Action("Index", "Talkgroup")",
            _viewRadioURL = "@Url.Action("Index", "Radio")",
            _searchData = Common.GetSearchData("@Model.SearchData.SearchDataEncoded");

        function TowerFrequencyDropDownListChange() {
            $("#FrequenciesGrid").data("kendoGrid").dataSource.read();
        }

        function GetFrequencySearchData() {

            return {
                frequencyType: $("#FrequencyTypeDropDownList").data("kendoDropDownList").value(),
                searchData: Common.GetSearchDataEncoded(_searchData)
            }
        }

        function GetNeighborSearchData() {

            return {
                searchData: Common.GetSearchDataEncoded(_searchData)
            }
        }
    </script>
}

Web/Views/Tower/Neighbors.cshtml
@using TowerNeighborService
@using TowerService

@model TowerDetailViewModel

@(Html.Kendo().Grid<TowerNeighborViewModel>()
    .Name("NeighborsGrid")
    .Columns(column =>
    {
        column.Bound(col => col.NeighborTowerNumber)
            .Title("Tower #")
            .Width(125)
            .Filterable(true);
        column.Bound(col => col.NeighborTowerName)
            .Title("Tower Name")
            .Filterable(filter => filter.Extra(false));
        column.Bound(col => col.NeighborControlChannel)
            .Title("Control Ch.")
            .Width(150)
            .Filterable(true);
        column.Bound(col => col.FirstSeen)
            .Format("{0:MM-dd-yyyy HH:mm}")
            .Width(150)
            .Filterable(true);
        column.Bound(col => col.LastSeen)
            .Format("{0:MM-dd-yyyy HH:mm}")
            .Width(150)
            .Filterable(true);
    })
    .ToolBar(toolbar =>
    {
        toolbar.Template(@<text>
                            <div class="toolbar-export">
                                <a href="#" class="k-button k-button-icontext k-grid-excel" title="Export data to Excel">
                                    <span class="k-icon k-i-excel"></span>Export
                                </a>
                            </div>
                        </text>);
    })
    .Filterable(filter =>
    {
        filter.Enabled(true);
        filter.Operators(operators =>
        {
            operators.ForNumber(number =>
                number.Clear()
                    .IsGreaterThanOrEqualTo(">=")
                    .IsLessThanOrEqualTo("<="));

            operators.ForString(str =>
                str.Clear()
                    .Contains("Contains"));

            operators.ForDate(date =>
                date.Clear()
                    .IsGreaterThanOrEqualTo(">=")
                    .IsLessThanOrEqualTo("<="));
        });
    })
    .Scrollable(scroll => scroll.Height(575))
    .Sortable(sort =>
        sort.SortMode(GridSortMode.SingleColumn)
            .AllowUnsort(false))
    .Pageable(pageable =>
        pageable.Input(true)
            .Refresh(true))
    .Selectable(selectable =>
        selectable.Mode(GridSelectionMode.Single)
            .Type(GridSelectionType.Row))
    .Events(events =>
        events.FilterMenuInit("Filters.TowerFilterFormats"))
    .Excel(excel =>
        excel.AllPages(true)
            .Filterable(true)
            .FileName($"TowerNeighbors-Sys{Model.SystemID}-T{Model.TowerNumber}.xlsx"))
    .DataSource(dataSource =>
        dataSource.Ajax()
            .PageSize(15)
            .ServerOperation(true)
            .Sort(sort => sort.Add("NeighborTowerNumber").Ascending())
            .Read(read => read.Action("GetNeighbors", "Tower", new { systemID = Model.SystemID, towerNumber = Model.TowerNumber })
                .Data("GetNeighborSearchData"))))

Web/Views/Tower/Patches.cshtml
@using PatchService
@using TowerService

@model TowerDetailViewModel

@(Html.Kendo().Grid<PatchDetailViewModel>()
        .Name("PatchesGrid")
        .Columns(column =>
        {
            column.Bound(col => col.FromTalkgroupID)
                .Title("From TG")
                .Width(125)
                .Filterable(true);
            column.Bound(col => col.FromTalkgroupName)
                .Title("Name")
                .Filterable(filter => filter.Extra(false));
            column.Bound(col => col.ToTalkgroupID)
                .Title("To TG")
                .Width(125)
                .Filterable(true);
            column.Bound(col => col.ToTalkgroupName)
                .Title("Name")
                .Filterable(filter => filter.Extra(false));
            column.Bound(col => col.FirstSeen)
                .Format("{0:MM-dd-yyyy HH:mm}")
                .Width(150)
                .Filterable(true);
            column.Bound(col => col.LastSeen)
                .Format("{0:MM-dd-yyyy HH:mm}")
                .Width(150)
                .Filterable(true);
            column.Bound(col => col.HitCount)
                .Title("Hit Count")
                .Format("{0:#,##0}")
                .Width(100)
                .Filterable(false);
        })
        .ToolBar(toolbar =>
        {
            toolbar.Template(@<text>
                                <div class="toolbar-export">
                                    <a href="#" class="k-button k-button-icontext k-grid-excel" title="Export data to Excel">
                                        <span class="k-icon k-i-excel"></span>Export
                                    </a>
                                </div>
                            </text>);
    })
    .Filterable(filter =>
    {
        filter.Enabled(true);
        filter.Operators(operators =>
        {
            operators.ForNumber(number =>
                number.Clear()
                    .IsGreaterThanOrEqualTo(">=")
                    .IsLessThanOrEqualTo("<="));

            operators.ForString(str =>
                str.Clear()
                    .Contains("Contains"));

            operators.ForDate(date =>
                date.Clear()
                    .IsGreaterThanOrEqualTo(">=")
                    .IsLessThanOrEqualTo("<="));
        });
    })
    .Scrollable(scroll => scroll.Height(575))
    .Sortable(sort =>
        sort.SortMode(GridSortMode.SingleColumn)
            .AllowUnsort(false))
    .Pageable(pageable =>
        pageable.Input(true)
            .Refresh(true))
    .Selectable(selectable =>
        selectable.Mode(GridSelectionMode.Single)
            .Type(GridSelectionType.Row))
    .Events(events =>
        events.DataBound("Grids.PatchesDataBound")
            .Change("Grids.PatchChange")
            .FilterMenuInit("Filters.RadioFilterFormats"))
    .Excel(excel =>
        excel.AllPages(true)
            .Filterable(true)
            .FileName($"TowerPatches-Sys{Model.SystemID}-T{Model.TowerNumber}.xlsx"))
    .DataSource(dataSource =>
        dataSource.Ajax()
            .PageSize(15)
            .ServerOperation(true)
            .Sort(sort => sort.Add("FromTalkgroupID").Ascending())
            .Read(read => read.Action("GetPatches", "Tower", new { systemID = Model.SystemID, towerNumber = Model.TowerNumber })
                .Data("DetailSearches.GetSearchData"))))