Web/Controllers/DatabaseController.cs
using DatabaseService;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Web.Helpers;

namespace Web.Controllers
{
    public class DatabaseController : BaseController
    {
        private IDatabaseService _databaseService;

        public DatabaseController(IDatabaseService databaseService) => _databaseService = databaseService;

        public async Task<ActionResult> Index()
        {
            try
            {
                ViewBag.Title = "Data Stats";

                return View(await _databaseService.GetDatabaseStatsAsync());
            }
            catch (Exception exception)
            {
                return HandleViewError(exception);
            }
        }
    }
}

Web/Views/Shared/_FilterDetail.cshtml
@using ServiceCommon

@model SearchDataViewModel

<div class="card">
    <div class="row">
        <div class="col">
            <h4 class="text-center">
                <strong>The Following Data Filters are In Effect</strong>
            </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4" style="text-align: right;">
            <strong>Active Only?</strong> : <em>@Model.SearchData.ActiveOnlyText</em>
        </div>
        <div class="col-md-4" style="text-align: center;">
            <strong>Date From</strong> : <em>@Model.SearchData.DateFromText</em>
        </div>
        <div class="col-md-4" style="text-align: left;">
            <strong>Date To</strong> : <em>@Model.SearchData.DateToText</em>
        </div>
    </div>
</div>

Web/Views/Shared/_GridLayout.cshtml
@Styles.Render("~/Content/css")
@RenderBody()
@RenderSection("scripts", required: false)
@Scripts.Render("~/bundles/web")

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Trunked Radio Info</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    	<link href="https://cdn.kendostatic.com/2023.1.117/styles/kendo.common.min.css" rel="stylesheet" type="text/css" />
	<link href="https://cdn.kendostatic.com/2023.1.117/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css" />
	<link href="https://cdn.kendostatic.com/2023.1.117/styles/kendo.dataviz.min.css" rel="stylesheet" type="text/css" />
	<link href="https://cdn.kendostatic.com/2023.1.117/styles/kendo.flat.min.css" rel="stylesheet" type="text/css" />
	<link href="https://cdn.kendostatic.com/2023.1.117/styles/kendo.dataviz.flat.min.css" rel="stylesheet" type="text/css" />
<style type="text/css">
        .k-grid td { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
    </style>
    	<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
	<script src="https://cdn.kendostatic.com/2023.1.117/js/jquery.min.js"></script>
	<script src="https://cdn.kendostatic.com/2023.1.117/js/jszip.min.js"></script>
	<script src="https://cdn.kendostatic.com/2023.1.117/js/kendo.all.min.js"></script>
	<script src="https://cdn.kendostatic.com/2023.1.117/js/kendo.aspnetmvc.min.js"></script>
	<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            @Html.ActionLink("Trunked Radio Info", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tools
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @Html.ActionLink("Radio Names", "RadioNames", "Tools", new { area = "" }, new { @class = "dropdown-item" })
                            @Html.ActionLink("Unknown Talkgroups", "UnknownTalkgroups", "Tools", new { area = "" }, new { @class = "dropdown-item" })
                        </div>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Data Stats", "Index", "Database", new { area = "" }, new { @class = "nav-link" })
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container-fluid body-content">
            @RenderBody()
        </div>
    </div>
    @Scripts.Render("~/")
    @Scripts.Render("~/bundles/datejs")
    @Scripts.Render("~/bundles/web")
    @RenderSection("scripts", required: false)
</body>
</html>